#!/bin/sh

tagHookName="[post-merge]"
warningMessage="info: "
copyGitHooks="copy-git-hooks.sh"

echo "$tagHookName $warningMessage"
echo "Verificando pre-requisitos para atualizacao dos hooks"
[ "$(basename $(pwd))" != "git-hooks" ] && echo "Skipped" || ( [ -f "$copyGitHooks" ] && chmod +x "$copyGitHooks" && echo "Executando o script '$copyGitHooks'" && ./$copyGitHooks --update-only-git-hooks )