#!/bin/sh

mensagemAviso="Aviso: "
tagHookName="[post-checkout]"
vFileGitModules=".gitmodules"
vCommandGitFetch="git fetch --recurse-submodules --prune"

currentBranchName="$(git branch | grep ^* | sed "s/*//" | sed "s/ //")"

if ! [[ "$currentBranchName" =~ "(" ]]; then
	if [ -f $vFileGitModules ]; then
		echo "$tagHookName $mensagemAviso"
		echo "Atualizando referencias locais com o repositorio remoto: '$vCommandGitFetch'"
		$vCommandGitFetch

		if [ "$?" -ne "0" ]; then
			echo -e "\033[1;31mNao foi possivel atualizar as referencias locais com o repositorio remoto\033[0m"
		fi
		
		echo ""

		echo "$tagHookName $mensagemAviso"
		echo "Posicionando nos branches correspondentes dos submodules"
		git submodule foreach --recursive "
			branchSubmodule=\$(git config -f \"\$toplevel/.gitmodules\" submodule.\$name.branch);

			if [ \"\$branchSubmodule\" = \".\" ]; then
				cd \"\$toplevel\";
				branchSuperproject=\$(git branch --show-current);
				cd \"\$sm_path\";
				
				git -c core.hooksPath=/dev/null checkout \$branchSuperproject || echo Nao foi possivel posicionar no branch \$branchSuperproject no submodule \"\$sm_path\"!;
			elif [ -n \"\$branchSubmodule\" ]; then
				git -c core.hooksPath=/dev/null checkout \$branchSubmodule || echo Nao foi possivel posicionar no branch \$branchSubmodule no submodule \"\$sm_path\"!;
			else
				echo Nao foi possivel posicionar no branch correspondente no submodule \"\$sm_path\", pois o branch nao foi especificado no arquivo .gitmodules do superprojeto!;
			fi;
		"
		echo ""

		if ! [[ "$(pwd)" =~ ^\/\/wsl\.localhost\/ ]]; then
			siagriGSKEnvironmentVariable=$SiagriGSK

			siagriGSKInstalled=false

			if [ -n "$siagriGSKEnvironmentVariable" ]; then
				searchReturn="$(type gsk)"

				if [ "$?" -eq "0" ]; then
					siagriGSKInstalled=true
				fi
			fi

			if [ "$siagriGSKInstalled" = true ]; then
				echo "$tagHookName $mensagemAviso"
				echo "Verificando branch corrente nos submodules que rastreiam o superprojeto..."

				listaSubmodules="$(gsk_show_submodules_path --only-tracking-branch)"

				if [ -n "${listaSubmodules[*]}" ]; then
					vDiretorioCorrente="$(show_current_directory)"
					vNomeBranchSuperprojeto="$(gsk_show_current_branch_name)"

					for path in ${listaSubmodules[*]}; do
						vDiretorioSubmodule="$vDiretorioCorrente/$path"

						if [ -f "$vDiretorioSubmodule/.git" ]; then
							if [ -d "$vDiretorioSubmodule" ]; then
								cd "$vDiretorioSubmodule"

								vNomeBranchSubmodule="$(gsk_show_current_branch_name)"

								if [ "$vNomeBranchSuperprojeto" != "$vNomeBranchSubmodule" ]; then
									erro "Nao foi possivel posicionar no branch '$vNomeBranchSuperprojeto' no submodule '$path'!"
									gsk_status
								fi
							else
								alerta "Nao foi possivel verificar o branch corrente no submodule '$path'! \nPois, o diretorio nao foi localizado: '$vDiretorioSubmodule'"
							fi
						else
							alerta "O submodule '$path' nao foi inicializado!"
						fi
					done

					cd "$vDiretorioCorrente"
				fi

				echo ""
			fi
		fi
	fi
else
	echo "$tagHookName Skipped: $currentBranchName"
fi

if [ -f "$(dirname "$0")/husky.sh" ]; then
	if ! [[ "$currentBranchName" =~ "(no branch, rebasing" ]]; then
		. "$(dirname "$0")/husky.sh"
	else
		echo "$tagHookName husky > Skipped: $currentBranchName"
	fi
fi