#!/bin/sh

tagHookName="[post-merge]"
copyGitHooks="copy-git-hooks.sh"

echo "$tagHookName Checking prerequisites for updating the hooks"
[ "$(basename $(pwd))" != "git-hooks" ] && echo "Skipped" || ( [ -f "$copyGitHooks" ] && chmod +x "$copyGitHooks" && echo "Running the script '$copyGitHooks'" && ./$copyGitHooks --update-only-git-hooks )