#!/bin/sh

tagHookName="[post-checkout]"
warningMessage="info: "
copyGitHooks="copy-git-hooks.sh"
vFileGitModules=".gitmodules"
vCommandGitFetch="git fetch --recurse-submodules --prune"

currentBranchName="$(git branch | grep ^* | sed "s/*//" | sed "s/ //")"

echo "$tagHookName $warningMessage"
echo "Current branch: $currentBranchName"
echo ""

isBranch=true
rebasing=false

if [[ "$currentBranchName" =~ "(" ]]; then
	isBranch=false

	# (no branch, rebasing branchName)
	if [[ "$currentBranchName" =~ "rebasing" ]]; then
		rebasing=true
	fi
fi

if [ "$isBranch" = true ]; then
	echo "$tagHookName $warningMessage"
	echo "Buscando referencias dos branches no repositorio remoto: '$vCommandGitFetch'"
	$vCommandGitFetch

	if [ "$?" -ne "0" ]; then
		echo -e "\033[1;31mNAO foi possivel buscar as referencias dos branches no repositorio remoto!\033[0m"
	fi
	
	echo ""

	echo "$tagHookName $warningMessage"
	echo "Verificando se ha submodule(s)"
	echo ""

	if [ -f $vFileGitModules ]; then
		echo "$tagHookName $warningMessage"
		echo "Posicionando nos branches correspondentes dos submodules que rastreiam o branch do superprojeto"
		git submodule foreach --recursive "
			branchSubmodule=\$(git config -f \"\$toplevel/.gitmodules\" submodule.\$name.branch);

			if [ \"\$branchSubmodule\" = \".\" ]; then
				cd \"\$toplevel\";
				branchSuperproject=\$(git branch --show-current);
				cd \"\$sm_path\";
				
				git -c core.hooksPath=/dev/null checkout \$branchSuperproject || echo Nao foi possivel posicionar no branch \$branchSuperproject no submodule \"\$sm_path\"!;
			elif [ -n \"\$branchSubmodule\" ]; then
				git -c core.hooksPath=/dev/null checkout \$branchSubmodule || echo Nao foi possivel posicionar no branch \$branchSubmodule no submodule \"\$sm_path\"!;
			else
				echo Nao foi possivel posicionar no branch correspondente no submodule \"\$sm_path\", pois o branch nao foi especificado no arquivo .gitmodules do superprojeto!;
			fi;
		"
		echo ""
	fi
fi

echo "$tagHookName $warningMessage"
echo "Verificando pre-requisitos para atualizacao dos hooks"
[ "$rebasing" = true ] && echo "Skipped" || ( [ -f "$copyGitHooks" ] && chmod +x "$copyGitHooks" && echo "Executando o script '$copyGitHooks'" && ./$copyGitHooks --update-only-git-hooks )