#!/bin/sh

tagHookName="[pre-commit]"
warningMessage="info: "
copyGitHooks="copy-git-hooks.sh"

echo "$tagHookName $warningMessage"
echo "Checking prerequisites for updating the hooks"
! [ -f "$copyGitHooks" ] && echo "Skipped" || ( chmod +x "$copyGitHooks" && echo "Running the script '$copyGitHooks'" && ./$copyGitHooks --update-only-git-hooks )