#!/bin/sh

tagHookName="[pre-push]"
warningMessage="info: "
copyGitHooks="copy-git-hooks.sh"

echo "$tagHookName $warningMessage"
[ "$(basename $(pwd))" = "git-hooks" ] && [ -f "$copyGitHooks" ] && chmod +x "$copyGitHooks" && echo "Executando o script '$copyGitHooks'" && ./$copyGitHooks --update-only-git-hooks