#!/bin/sh

tagHookName="[pre-commit]"
warningMessage="info: "
copyGitHooks="copy-git-hooks.sh"

echo "$tagHookName $warningMessage"
echo "Verificando pre-requisitos para atualizacao dos hooks"
! [ -f "$copyGitHooks" ] && echo "Skipped" || ( chmod +x "$copyGitHooks" && echo "Executando o script '$copyGitHooks'" && ./$copyGitHooks --update-only-git-hooks )