#!/bin/sh

tagHookName="[pre-push]"
warningMessage="info: "
copyGitHooks="copy-git-hooks.sh"

echo "$tagHookName $warningMessage"
echo "Checking prerequisites for updating the hooks"
[ "$(basename $(pwd))" != "git-hooks" ] && echo "Skipped" || ( [ -f "$copyGitHooks" ] && chmod +x "$copyGitHooks" && echo "Running the script '$copyGitHooks'" && ./$copyGitHooks --update-only-git-hooks )